spring.application.name=x6_product
springdoc.swagger-ui.path=/swagger-ui
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/x6_product
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD}
spring.liquibase.change-log=/db/changelog/db.changelog-master.yaml
spring.data.redis.host=localhost
spring.data.redis.port=6379